dist: xenial
language: python
env:
  global:
    - secure: Dt8788LkTH1v6ZyPX92bkQ04I1O/Dg4agyM8q4Ehvn3rLGOghqef76+PLnMl8IjhFjchxthN2P3LxVT0yUEnuTA4ymZP3xqYquvD/C44nqT60+YaeI3ZW3SYiWGWqX15tR2FJ3/T+NNANy2gP6rStfT5EfYjDWXmlm8hhNXSFwwuQsQK3NA4DRVOy++aHvw02l/J6z2Pc2/fBbL96BNyAFDPsnYqC6BlgCYnnyuAhFXZsyp4RAOV7qpDaM5nrQPYSlCnlaOT7b0MIzLdNfRDjvKHRiqBYMC/vEPfhNvcT7gy+R8E2OFwjt9qAc/WDTQtbu03J7dL/XeivtYVmsudjqmDciChGHVNg8yO2DeAx7qimWGe8Ac6vfjB18IHpJZZWgxzfIWFZpepRUTRabBe3RA8qtBrLfDXlPYW5AEWJ4/tviO5XEs8TD2RxwP2BGiGTbkCb6BlNKQ8EEiI60oUTftlTQ2OdakVMnOYSa0YsMwfhfAy1BfPrFlYbJ3tKfrrnaDmXGNus4ukwGYoexM7Ioe8wJeOx/bM1AqgkzSCEczdrRyZrYaD0ictmFlJ96eiCZgeOx9+QC7Ak/GGAZACNDpILbncVWU13iIgjEYFRHbvLAPhnyf16o82yme73hYcxmKuCyDD+dKNssLQyxDsVyEr8PFSOEGdxDALOaZhlyg=

matrix:
  include:
    - python: '3.6'
      env: NOXSESSION=tests-3.6
    - python: '3.7'
      env: NOXSESSION=tests-3.7
    - python: '3.8'
      env: NOXSESSION=tests-3.8
    - python: '3.8'
      env: NOXSESSION=lint
    - python: '3.8'
      env: NOXSESSION=docs

install: pip install -U pip setuptools nox

script: nox -s $NOXSESSION

deploy:
  provider: script
  script: nox -s deploy
  on:
    tags: true
    branch: master
    repo: lewoudar/ib_client
    condition: "$NOXSESSION = tests-3.8"
