init:
  - SET PATH=%PYTHON%;%PATH%

environment:
  CODECOV_TOKEN:
    secure: hyKxQazxzW9GQ7M5tFI4jZVRLo1iAgl1gkepHQSO+BWjv2rR8Dp2lu+19JksQyH2

  matrix:
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37-x64

install:
  - python -m pip install pipenv
  - python -m pipenv install --dev

build: off

test_script:
  - python -m pipenv run flake8
  - python -m pipenv run bandit -r infoblox
  - python -m pipenv run pytest

after_test:
  - python -m pipenv run codecov
  - python -m pipenv run python setup.py bdist_wheel

artifacts:
  - path: dist\*